### ISSUE TITLE
yocs_velocity_smoother inner thread is never run actually.

### ISSUE THREAD

**Issue by asimay** [yujinrobot/yujin_ocs#101]
yocs_velocity_smoother inner thread is never run really. no smooth_cmd_vel topics run..

![00](https://cloud.githubusercontent.com/assets/8703449/15568413/58d36f8c-235e-11e6-87cf-b1cc178f8bd7.png)

**Comment by asimay** [comment]
Just only have node run, but no any useful topics output.
is there any body can instruct me? Thanks!

**Comment by stonier** [comment]
How did you launch it exactly?

If you are launching it as a nodelet in a nodelet manager, then you need to do `rosnode info` on the manager (which is where it runs). Quite likely doing it on `/velocity_smoother` runs it on the nodelet loader, which actually isn't running the code.

**Comment by asimay** [comment]
hi, dear @stonier , thank you very much. I really carelessness, I didn't check whether the launch load the nodelet manager or not,  I solved this when load nodelet manager. thank you very much!
