### ISSUE TITLE
 I want to know how to use the yocs_waypoints navi package ,launch the xxx.launch failed

### ISSUE THREAD

**Issue by liushengkai008** [yujinrobot/yujin_ocs#109]
I want to know how to use the yocs_waypoints navi package ,launch the xxx.launch failed.
i download the package but i dont know houto use it on turtlebot ,i don't find the realated introduce to use it  
i  need your help,thank u

**Comment by stonier** [comment]
We don't actually use/support this package any longer as we have since moved to another solution. Consider it deprecated, but feel free to pick it up and use it yourself.
