### ISSUE TITLE
Timeouts do not stop robot motion

### ISSUE THREAD

**Issue by dawonn** [yujinrobot/yujin_ocs#16]
Shouldn't the mux output a zero cmd_vel when the timeout expires? 

Or is that purely the responsibility of the robot driver to make sure it's getting commands consistently?  Is there a REP of some sort that defines this behavior?

**Comment by corot** [comment]
Well, it's intended to just multiplex velocity commands, not to modify them. But velocity_smoother does what you mention, and also kobuki_node has such a timeout. That should be enough in most cases.

**Comment by dawonn** [comment]
I added logic to my robot's driver node to stop the robot if no commands are received during a timeout period. I guess I'll pretend this is the 'standard' ;)
