### ISSUE TITLE
velocity smoother keeps publishing velocities

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#2]
even when the publisher stops publishing, e.g. rostopic command line tool.
Have seen that in other cases as well.

**Comment by bit-pirate** [comment]
also, make sure that the velocity smoother smooths to zero, if a publisher stops sending velocity commands, e.g. connection lost.

**Comment by corot** [comment]
I must tell in my discharge that is not a bug, but an artifact generated for sending isolated commands (the timeout was already there, but proportional to the calculated frequency)
