### ISSUE TITLE
Re-release with new bloom

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#28]
There is an issue with optimisation and debug flags not set, when doing release with an old bloom version (<0.5.8) for Quantal, Raring and Trusty for both Hydro and Indigo.

Whenever convenient we should do a re-release of all YOCS packages for Hydro and Indigo.

Details here: http://lists.ros.org/pipermail/ros-users/2014-May/068657.html

**Comment by jihoonl** [comment]
done
