### ISSUE TITLE
keep direction constant when smoothing velocities

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#3]
Currently the velocity smoother adjusts the velocities independently, what can cause the original velocity heading (vector orientation) to be modified as well.

Please adjust the smoothing in the way that the original heading is not changed.

**Comment by corot** [comment]
We should rename this package to diff_drive_vel_smoother or something like that. Sooner or latter we will have an omni base a then I will recover the previous version smoothing each dof separately.
