### ISSUE TITLE
[Velocity smoother] Zeroing out velocity in the middle of navigation...

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/yujin_ocs#33]
When does this happen?

```
[ WARN] [1401959005.438486434]: Velocity Smoother : input got inactive leaving us a non-zero target velocity (0, -1), zeroing...[navigation_velocity_smoother]
```

![velocity_smotther](https://cloud.githubusercontent.com/assets/1556736/3185232/cbb570ce-ec90-11e3-8131-741ee503c33f.png)

**Comment by corot** [comment]
Typically if the navigation plan fails: navi stack abruptly stop sending cmd_vel messages, so the last one often is not a 0.0, 0.0 velocity. Here the Velocity Smoother slows down gently to zero velocity.

**Comment by stonier** [comment]
Saw this happening when the navi stack was sending small rotational velocity commands (i.e. < 0.1 rad/s). Another symptom was the robot just didn't do those low velocity rotate recoveries at all (low velocity commands got sucked out somewhere). I'll get rid of the navi stack factor and fake some small input commands and get some more data.

**Comment by stonier** [comment]
The following was generated by running a simple test script on top of the turtlebot amcl_demo launch. The script oscillates the rotational command between -0.2 and 0.2.

![smoother](https://cloud.githubusercontent.com/assets/687378/3225006/b3dcd4ca-f045-11e3-86fb-1626c37b04b4.png)

Note - the smoother zeroes the velocity thrice at each end with the corresponding message above showing.

**Comment by stonier** [comment]
Ah - there is a basic assumption in the velocity smoother.

_incoming cmd_vel messages are streamed at a constant trate_

The above test breaks that - it publishes at 20hz when changing the velocity and only 5hz otherwise. The velocity smoother has a zeroing timeout that triggers if it thinks it has been 3 times the expected callback period since the last message.

**Comment by stonier** [comment]
Now need to check if the navigation rotate recoveries are doing the same thing.

**Comment by stonier** [comment]
I think we can close this - the assumption is reasonable and isn't the real problem we have (see https://github.com/yujinrobot/kobuki-x/issues/32).
