### ISSUE TITLE
Why are .project and .cproject files on src directory on packages yocs_ar_marker_tracking and yocs_ar_pair_tracking?

### ISSUE THREAD

**Issue by corot** [yujinrobot/yujin_ocs#37]
Also they are missing for yocs_ar_pair_approach

**Comment by stonier** [comment]
Which branches?

**Comment by stonier** [comment]
I can't remember doing it but looks like I already discovered yocs_ar_marker_tracking's files in indigo branch.

f3fc67c0907a7071999904771a025b9605136d42

**Comment by stonier** [comment]
Also removed from yocs_ar_pair_tracking in 8363f934cfd10b45e9e52690e2b93b0d0df492d8.

These are cherry-picked back to hydro-devel. Feel free to create eclipse files elsewhere.
