### ISSUE TITLE
Catkinize

### ISSUE THREAD

**Issue by stonier** [yujinrobot/yujin_ocs#4]

**Comment by stonier** [comment]
Dont forget to update ros/rosdistro's doc branch to probably groovy-devel.

**Comment by corot** [comment]
that's what you did yesterday, right?

**Comment by stonier** [comment]
No, we went back from groovy-devel to groovy since that is what the old rosrelease-legacy creates by default.

**Comment by corot** [comment]
Alea jacta est...
