### ISSUE TITLE
Develop interactive waypoint editor

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#47]
@corot already developed a tool to specify a path along multiple waypoints using RViz (see `yocs_waypoint_navi`). Maybe we can extend this approach. Otherwise we an RViz or rQt plugin might be the way to go.

In any case this feature should be implemented within the `yocs_waypoint_provider` and dropped from `yocs_waypoints_navi`.

This is a follow-up of https://github.com/yujinrobot/yujin_ocs/issues/41.

**Comment by 130s** [comment]
Just hit this ticket while I was googling waypoint viewer and editor (for MoveIt! though). Does this feature work with `yocs` only? If not what would be the requirement?

I wrote `rqt_moveit` awhile ago with minimal monitoring functionalities, and now I'm willing to enhance it with some operations for trajectories.

Thanks.
Fyi @terakoji

**Comment by bit-pirate** [comment]
@130s what kind of trajectories/waypoints would you like to define?

Currently we use `yocs_msgs/Waypoint` (https://github.com/yujinrobot/yocs_msgs/blob/indigo-devel/msg/Waypoint.msg), which is basically a stamped pose with a name.

**Comment by 130s** [comment]
I'm thinking of my applications only as a starter, so the waypoints [used in MoveIt!](http://docs.ros.org/hydro/api/pr2_moveit_tutorials/html/planning/scripts/doc/move_group_python_interface_tutorial.html), which is just an array of `geometry_msgs/Pose`.

I found btw [nav_msgs/Path](http://docs.ros.org/api/nav_msgs/html/msg/Path.html) that seems to be pretty similar to `yocs_msgs/Waypoint`.

**Comment by bit-pirate** [comment]
> I'm thinking of my applications only as a starter, so the waypoints used in MoveIt!, which is just an array of geometry_msgs/Pose.

Our use case is for (planar) navigation and would probably (at first) only support 2D position + orientation. Would this be useful for you as well or do you need it to specify 3D poses, e.g. for manipulation?

> I found btw nav_msgs/Path that seems to be pretty similar to yocs_msgs/Waypoint.

You are right. However, we need to have names assigned to each pose in order to identify them.
