### ISSUE TITLE
Python version of basic_move_controller used?

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#66]
There is a python library replicating the C++ version of the basic_move_controller, but I cannot find any script using it.

@jihoonl do you know, if it is used?

**Comment by jihoonl** [comment]
It is used it here. localisation manager is under development though yet

https://github.com/yujinrobot/yujin_ocs/blob/indigo/yocs_localization_manager/src/yocs_localization_manager/localization_manager.py#L11
