### ISSUE TITLE
release packages in indigo.ignored

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/yujin_ocs#68]
The [packages](https://github.com/yujinrobot-release/yujin_ocs-release/blob/master/indigo.ignored) are intentionally not released yet. 
- yocs_localization_manager is still under development.
- yocs_navigator need to get merged with yocs_waypoints_navi.

Then these packages will also be released.

**Comment by jihoonl** [comment]
also
- yocs_ar_marker_tracking
- yocs_ar_pair_tracking
- yocs_ar_pair_approach
- yocs_waypoint_provider

**Comment by jihoonl** [comment]
#63 was a reason not to release yocs_ar_\* and waypoint_provider. It should be ready to release as of now.

**Comment by stonier** [comment]
These seem to be now getting released, so closing this issue.
