### ISSUE TITLE
replace table with waypoint

### ISSUE THREAD

**Issue by jihoonl** [yujinrobot/yujin_ocs#73]
[Table.msg](https://github.com/yujinrobot/yocs_msgs/blob/indigo-devel/msg/Table.msg) has been used to indicate a location with name.

After discussion with @bit-pirate, Table.msg will be merged with [Waypoint.msg](https://github.com/yujinrobot/yocs_msgs/blob/indigo-devel/msg/Waypoint.msg)
- [x] yujin_ocs
- [x] concert_qt_map_annotation
- [x] rocon_demos
- [ ] data in xavier and alien
- [x] authoring
- [x] webapps

**Comment by jihoonl** [comment]
- yujin_ocs : https://github.com/yujinrobot/yujin_ocs/tree/table_cleanup
- rocon_qt_gui : https://github.com/robotics-in-concert/rocon_qt_gui/tree/table_cleanup
- rocon_demos
  - https://github.com/robotics-in-concert/rocon_demos/tree/table_cleanup
  - https://github.com/robotics-in-concert/rocon_demos/tree/table_cleanup_rapp

**Comment by jihoonl** [comment]
Table -> Waypoint converter has been developed. https://github.com/robotics-in-concert/rocon_demos/blob/table_cleanup/scripts/concert_table_to_waypoint.py

**Remain job**
- [x] update authoring tool to use waypoint msg
- [x] update webapps to parse weypoint msg
- [x] convert data in xavier and alien
- [x] Test our demos
- [x] Test to add and remove annotations.

**Comment by dwlee** [comment]
I updated following jobs
- Update authoring tool to use waypoint msg
- Update webapps to parse weypoint msg
  -  https://github.com/robotics-in-concert/rocon_web_gui/pull/7
  -  https://github.com/robotics-in-concert/rocon_web_gui/pull/8
- Test our demos
  - pickup delivery test complete
  - vm delivery test complete
- Complete db converting in xavier
  - https://github.com/robotics-in-concert/rocon_demos/tree/demo_concert_table_cleanup/annotations
