### ISSUE TITLE
Ros wiki documentation

### ISSUE THREAD

**Issue by stonier** [yujinrobot/yujin_ocs#8]
Update.

**Comment by corot** [comment]
I just create a template pages that load the short description from manifest.xml.  Enough?

**Comment by stonier** [comment]
If it's going to be fairly stable for the rest of groovy we need to do like the kobuki_node. 
- about section
- params
- dynamic parameters
- publishers, subscribers, services, action_servers

And if you want to be really nice, a tutorial or two. Since it's quite visible in turtlebot, it's important. But even without turtlebot - if those pages are there, it's then really easy for the next person at Yujin to pick up and re-use those components. Digging through source code to work things out takes hours.

**Comment by corot** [comment]
As I'm just partially nice, I give a reference to Kobuki's Control System Tutorial, who covers well all these stuff.
