### ISSUE TITLE
[cmd_vel_mux] Plan for release into Indigo?

### ISSUE THREAD

**Issue by 130s** [yujinrobot/yujin_ocs#86]
I see some tickets about pending release, e.g. https://github.com/yujinrobot/yujin_ocs/issues/36#issuecomment-48262979
I'm interested in seeing `cmd_vel_mux` in Indigo as deb. Is this not likely to happen?

**Comment by bit-pirate** [comment]
Should already be available: http://www.ros.org/debbuild/indigo.html?q=yocs_cmd_vel_mux

**Comment by 130s** [comment]
Ah, didn't notice the name changed. Thx!
