### ISSUE TITLE
fix warning introduced by new catkin version

### ISSUE THREAD

**Issue by bit-pirate** [yujinrobot/yujin_ocs#9]
Fix this warning:

```
WARNING: The metapackage 'yujin_ocs' has no CMakeLists.txt. Please add one to the package source. You can use the following file: /opt/kobuki_workspace/catkin_ws/build/catkin_generated/metapackages/yujin_ocs/CMakeLists.txt
```

**Comment by jihoonl** [comment]
It has been fixed in the hydro-devel. You may want to cherry-pick.

https://github.com/yujinrobot/yujin_ocs/commit/86c184028c5f1378ec5015940a9ccdac4bc18f2e

**Comment by bit-pirate** [comment]
The comitter of that fix should have cherry-pick it.

2013/4/15 Jihoon Lee notifications@github.com

> It has been fixed in the hydro-devel. You may want to cherry-pick.
> 
> 86c1840https://github.com/yujinrobot/yujin_ocs/commit/86c184028c5f1378ec5015940a9ccdac4bc18f2e
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/yujinrobot/yujin_ocs/issues/9#issuecomment-16363797
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by jihoonl** [comment]
done.

**Comment by bit-pirate** [comment]
Thank you!
